/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#c8c6c5',
        'error': '#ba1a1a',
        'inverse-primary': '#fabd00',
        'on-primary-container': '#6d5100',
        'on-error': '#ffffff',
        'surface-variant': '#e2e2e2',
        'primary-fixed-dim': '#fabd00',
        'on-tertiary-fixed-variant': '#474744',
        'on-secondary-fixed': '#1c1b1b',
        'background': '#f9f9f9',
        'surface-container-high': '#e8e8e8',
        'primary': '#785900',
        'on-error-container': '#93000a',
        'on-surface': '#1a1c1c',
        'inverse-surface': '#2f3131',
        'surface-bright': '#f9f9f9',
        'error-container': '#ffdad6',
        'outline-variant': '#d4c5ab',
        'secondary': '#5f5e5e',
        'on-secondary': '#ffffff',
        'surface-tint': '#785900',
        'tertiary': '#5e5e5c',
        'surface-container': '#eeeeee',
        'surface': '#f9f9f9',
        'secondary-fixed': '#e5e2e1',
        'on-primary-fixed': '#261a00',
        'inverse-on-surface': '#f0f1f1',
        'on-secondary-fixed-variant': '#474746',
        'on-tertiary': '#ffffff',
        'on-background': '#1a1c1c',
        'tertiary-container': '#cccbc7',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#4f4632',
        'outline': '#827660',
        'on-secondary-container': '#636262',
        'surface-container-highest': '#e2e2e2',
        'surface-container-low': '#f3f3f4',
        'primary-fixed': '#ffdf9e',
        'on-primary-fixed-variant': '#5b4300',
        'primary-container': '#ffc107',
        'tertiary-fixed': '#e4e2de',
        'surface-dim': '#dadada',
        'on-tertiary-fixed': '#1b1c1a',
        'tertiary-fixed-dim': '#c8c6c3',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#555653',
        'secondary-container': '#e2dfde',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'base': '8px',
        'margin-desktop': '80px',
        'gutter': '24px',
        'max-width': '1280px',
        'margin-mobile': '20px',
      },
      maxWidth: {
        'max-width': '1280px',
      },
      fontFamily: {
        headline: ['Bebas Neue', 'sans-serif'],
        display: ['Bebas Neue', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Be Vietnam Pro', 'sans-serif'],
        grotesk: ['Hanken Grotesk', 'sans-serif'],
        jakarta: ['Plus Jakarta Sans', 'sans-serif'],
        julius: ['Julius Sans One', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'fade-out': 'fadeOut 0.3s ease-out forwards',
        'fade-out-down': 'fadeOutDown 0.3s ease-out forwards',
        'scale-in': 'scaleIn 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-down': 'slideDown 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        fadeOutDown: {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(20px)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9) translateY(20px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
